### ISSUE TITLE
failed to generate valid assembly for instruction

### ISSUE THREAD

**Issue by xtreh** [asmjit/asmtk#14]
failed to generate valid assembly for instruction:
`fstp qword ptr fs:[rcx], st0`

**Comment by kobalicek** [comment]
The following works `fstp qword ptr fs:[rcx]`

The instruction database says there is only one operand as all instructions that pop the stack have the `st0` implicit. Are there actually assemblers that would accept 2 operand form in this case?

**Comment by kobalicek** [comment]
Closing, if this is a problem please reopen.
