### ISSUE TITLE
push register not working!

### ISSUE THREAD

**Issue by overtech1** [asmjit/asmtk#15]
sentences like push eax , or pushad not parse but push 0x11111111 works fine.
it say "Invalid instruction" error.
can someone help me??

**Comment by kobalicek** [comment]
`push eax` - 32-bit mode
`push rax` - 64-bit mode

**Comment by overtech1** [comment]
> 
> 
> `push eax` - 32-bit mode
> `push rax` - 64-bit mode
> 
> https://asmjit.com/asmgrid - provides all instructions and their signatures supported by asmjit.

Excuse me, I mean asmtk parser not parse this instruction not the asmjt. can u help me please?

**Comment by kobalicek** [comment]
It parses both instructions successfully, just select the right architecture and try it here:
  https://kobalicek.com/fiddle-asmtk.html

**Comment by overtech1** [comment]
> 
> 
> It parses both instructions successfully, just select the right architecture and try it here:
> https://kobalicek.com/fiddle-asmtk.html

Thank you very much! It solved my problem, that was architecture miss configuration
