### ISSUE TITLE
assembler.sub(x86::ptr(x86::esp, 3), 0x4444); Not Compile!

### ISSUE THREAD

**Issue by overtech1** [asmjit/asmtk#18]
assembler.sub(x86::ptr(x86::esp, 3), 0x4444);

this instruction not compile and return nothing!

**Comment by kobalicek** [comment]
Have you checked the error? I would assume "ambiguous operand size", and I think it explains the problem very well. It would be dangerous to guess the size.

**Comment by overtech1** [comment]
changing the ptr to dword_ptr fixed the issue. thank you
