### ISSUE TITLE
MSVC compiler warnings

### ISSUE THREAD

**Issue by codecat** [asmjit/asmtk#20]
Getting the following warnings when building on 64 bit MSVC:

```
asmtk\asmparser.cpp(1075,9): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data
asmtk\asmparser.cpp(1152,39): warning C4267: 'initializing': conversion from 'size_t' to 'uint32_t', possible loss of data
```

That's these 2 lines:
https://github.com/asmjit/asmtk/blob/6930021adb770b23ac23273e913982af2e9c15b1/src/asmtk/asmparser.cpp#L1075
https://github.com/asmjit/asmtk/blob/6930021adb770b23ac23273e913982af2e9c15b1/src/asmtk/asmparser.cpp#L1152

**Comment by kobalicek** [comment]
Thanks!

I will fix these soon as this needs fixing both AsmJit and AsmTK:
  - AsmJit to accept size_t in embed(), which fixes the first issue
  - AsmTK to use size_t in the second case.

**Comment by kobalicek** [comment]
Both warnings should be fixed by now.
