### ISSUE TITLE
X64  MOV RSP,8  why mov esp,8

### ISSUE THREAD

**Issue by icyfox168168** [asmjit/asmtk#23]
x64dbg
// XED
00007FFC9220063A | 48:C7C4 08000000                                  | mov rsp,8                                             |
//ASMJIT
00007FFC92200641 | BC 08000000                                       | mov esp,8                                             |

**Comment by kobalicek** [comment]
You use an old asmjit, this used to be an optimization, but it's off by default. AsmJit correctly assembles `mov rsp, 8` to `48C7C4 08000000`.

**Comment by icyfox168168** [comment]
I tested the latest version correctly, it should be x64DBg did not update the corresponding asmjit.dll

**Comment by kobalicek** [comment]
Thanks for confirmation, closing
