### ISSUE TITLE
Syntax is not fully compatible

### ISSUE THREAD

**Issue by w4454962** [asmjit/asmtk#29]
"push [ecx]" needs to be changed to "push dword [ecx]" to be compiled,

In addition, if "AsmParser:: parse" has errors in multiple lines of code, you need to delete them one line at a time to eliminate the errors. No line number or error location is returned.

**Comment by kobalicek** [comment]
Hello, there are two variations of push [mem],

X86:

```
push word [rax]
push dword [rax]
```

X86_64:

```
push word [rax]
push qword [rax]
```

AsmJit needs the size to decide which one to encode as `push [rax]` is ambiguous. I know that some other assemblers assume the memory operand has a register size, but AsmJit needs this explicitly.

If you need to parse individual commands, you can do what `AsmParser::parse()` does manually:

```
Error AsmParser::parse(const char* input, size_t size) noexcept {
  setInput(input, size);
  while (!isEndOfInput())
    ASMJIT_PROPAGATE(parseCommand());
  return kErrorOk;
}
```

Basically `AsmParser::parse()` is a high-level call, assembling the whole program. Going command by command you can react to errors, but I think it's kinda useless as other errors may depend on previous errors.

**Comment by w4454962** [comment]
OK, I have completed the replacement of my assembler. Compared with keystone, I only need two differences. One is the above, and the other is that the keystone begins with the comment "//". The only difficulties encountered in the process are that the errors are difficult to locate. Everything else is very good. I have solved them. I hope that the following people will not encounter them again. Thank you for your reply. The asmjit is excellent

**Comment by petr-sneller** [comment]
Adding support for `//` comments would be pretty easy. Fixing push too, although that's controversial whether asmtk should fixup that instruction.

If you need `//` comments please open an issue and I will look into it over the weekend.

**Comment by kobalicek** [comment]
Adding support for // comments would be pretty easy. Fixing push too, although that's controversial whether asmtk should fixup that instruction.

If you need // comments please open an issue and I will look into it over the weekend.
