### ISSUE TITLE
Short jump command with an out of range address isn't rejected

### ISSUE THREAD

**Issue by RaMMicHaeL** [asmjit/asmtk#4]
For example, if `EIP` is `0x1000`, and I assemble `jmp short 0x2000`, the command should be rejected, because the displacement is larger than ±`0x7F`.
I assume that the relevant code is around here:
https://github.com/asmjit/asmtk/blob/4fc156842d8458a44cb2a1f37f1a24c3ac5a4765/src/asmtk/asmparser.cpp#L708-L711

**Comment by kobalicek** [comment]
Hey, thanks for reporting this, however, this has to be fixed in asmjit as asmtk just parses the asm, but asmjit's responsibility is to validate and encode it.

AsmJit issue: https://github.com/asmjit/asmjit/issues/138

**Comment by RaMMicHaeL** [comment]
Thanks for the fix!
